version: 2.1

parameters:
  environment:
    type: string
    default: "qaprod"
  tags:
    type: string
    default: "@SmokeTest"
  email:
    type: string
    default: "ujwal.kumar@winmore.io"

jobs:
  run-playwright-tests:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout

      - run:
          name: Install Maven
          command: sudo apt-get update && sudo apt-get install -y maven

      - run:
          name: Install Playwright Browsers
          command: mvn exec:java -e -D exec.mainClass=com.microsoft.playwright.CLI -D exec.args="install --with-deps"

      - run:
          name: Run Tests - Environment:<< pipeline.parameters.environment >> Tag:<< pipeline.parameters.tags >>
          command: mvn clean test -Denvironment=<< pipeline.parameters.environment >> -Dcucumber.filter.tags="<< pipeline.parameters.tags >>" -DmailRecipients=<< pipeline.parameters.email >>

      - store_artifacts:
          path: target/surefire-reports
          destination: test-reports

      - store_artifacts:
          path: Reports
          destination: reports

workflows:
  manual-trigger:
    jobs:
      - run-playwright-tests